# This is a basic workflow to help you get started with Actions

name: Python package

# Команда, контролирующая запуск сборки
on:
  # Сборка запускается каждый раз при коммите файлов в папке проекта
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Позволяет запускать сборку вручную из вкладки Actions
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          architecture: 'x64'
      - name: Before install
        run: chmod +x ./flaskapp/st.sh
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install gunicorn
          pip install requests
          pip install tensorflow
          pip install flask-wtf
          pip install pillow
          pip install flask-bootstrap
          pip install keras
          pip install protobuf==3.20.1
          pip install h5py==2.10.0
          pip install lxml
      - name: Script
        run: |
          cd flaskapp
          ./st.sh
