# This is a basic workflow to help you get started with Actions

name: Python package

# Команда, контролирующая запуск сборки
on:
  # Сборка запускается каждый раз при коммите файлов в папке проекта
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Позволяет запускать сборку вручную из вкладки Actions
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
          architecture: 'x64'
      - name: Before install
        run: chmod +x ./flaskapp/st.sh
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask==1.1.2
          pip install gunicorn=20.0.4
          pip install requests==2.23.0
          pip install tensorflow==2.0.0
          pip install flask-wtf==0.14.3
          pip install pillow==6.2.2
          pip install flask-bootstrap==3.3.7.1
          pip install keras==2.3.1
      - name: Script
        run: |
          cd flaskapp
          ./st.sh
